---
- name: Provisionar máquina virtual no VMware Workstation
  hosts: localhost
  connection: vmnet8
  vars:
    vm_name: "linux-apache"
    template_path: "C:\Users\valdeci\Documents\Virtual Machines\Oracle_Linux_Template\Oracle_Linux_Template.vmx"
    guest_os: "oracle-64"
    vm_path: "C:\Users\valdeci\Documents\Virtual Machines"
    memory: 2048
    cpus: 2
    network_adapters:
      - type: nat

  tasks:
    - name: Clonar VM a partir do template
      community.vmware.guest:
        vm_name: "{{ vm_name }}"
        template: "{{ template_path }}"
        state: present
        guest_os: "{{ guest_os }}"
        path: "{{ vm_path }}/{{ vm_name }}.vmx"
        memory: "{{ memory }}"
        num_cpus: "{{ cpus }}"
        network: "{{ network_adapters }}"